server:
  port: 9000
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        incoming-tweets:
          destinations: tweet
          contentType: application/json
      metrics:
        key:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer


management:
  endpoints:
    web:
      exposure:
        include: "*"